// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type RecentReply struct {
	ID          string  `json:"id"`
	Title       *string `json:"title"`
	LastReplyAt *string `json:"last_reply_at"`
	Author      *User   `json:"author"`
}

type RecentTopic struct {
	ID          string  `json:"id"`
	Title       *string `json:"title"`
	LastReplyAt *string `json:"last_reply_at"`
	Author      *User   `json:"author"`
}

type Reply struct {
	ID       string    `json:"id"`
	Content  *string   `json:"content"`
	CreateAt *string   `json:"create_at"`
	ReplyID  *string   `json:"reply_id"`
	IsUped   *bool     `json:"is_uped"`
	Ups      []*string `json:"ups"`
	Author   *User     `json:"author"`
}

type Topic struct {
	ID          string  `json:"id"`
	AuthorID    string  `json:"author_id"`
	Tab         *string `json:"tab"`
	Content     *string `json:"content"`
	Title       string  `json:"title"`
	LastReplyAt *string `json:"last_reply_at"`
	Good        *bool   `json:"good"`
	Top         *bool   `json:"top"`
	ReplyCount  *int    `json:"reply_count"`
	VisitCount  *int    `json:"visit_count"`
	CreateAt    *string `json:"create_at"`
	IsCollect   *bool   `json:"is_collect"`
	Author      *User   `json:"author"`
}

type TopicDetail struct {
	ID          string   `json:"id"`
	AuthorID    string   `json:"author_id"`
	Tab         *string  `json:"tab"`
	Content     *string  `json:"content"`
	Title       string   `json:"title"`
	LastReplyAt *string  `json:"last_reply_at"`
	Good        *bool    `json:"good"`
	Top         *bool    `json:"top"`
	ReplyCount  *int     `json:"reply_count"`
	VisitCount  *int     `json:"visit_count"`
	CreateAt    *string  `json:"create_at"`
	IsCollect   *bool    `json:"is_collect"`
	Replies     []*Reply `json:"replies"`
	Author      *User    `json:"author"`
}

type User struct {
	Loginname *string `json:"loginname"`
	AvatarURL *string `json:"avatar_url"`
}

type UserDetail struct {
	Loginname      *string        `json:"loginname"`
	AvatarURL      *string        `json:"avatar_url"`
	GithubUsername *string        `json:"githubUsername"`
	CreateAt       *string        `json:"create_at"`
	Score          *int           `json:"score"`
	RecentReplies  []*RecentReply `json:"recent_replies"`
	RecentTopics   []*RecentTopic `json:"recent_topics"`
}
